In [16]:
%time l = range(1000000)
print(l)

Wall time: 0 ns
range(0, 1000000)


In [11]:
import numpy as np

In [26]:
# Simple methods
import numpy as np
x = np.array([55, 78, 9, 8, 7])
x.sum()



157

x.sum()

In [40]:
# Max num
print("The Highest Number is",x.max())
print("The index Highest Number is",x.argmax())

The Highest Number is 78
The index Highest Number is 1


In [42]:
# Min num
print("The smallest Number is",x.min())
print("The index of smallest Number is",x.argmin())

The smallest Number is 7
The index of smallest Number is 4


In [57]:

# Logical "AND" operation of a boolean array
np.any([False, True, True, True])

True

In [59]:

# Logical "OR" operation of a boolean array
np.any([False, True, True, True])

True

In [65]:
# Setting all the elements of an array to 0
a = np.zeros((121, 10, 150, 0)) #np.zeros convrt every element of arrray to 0
print(a)
print(np.any(a != 0)) # any search for any 1 in array
np.all(a != 0) # all function is used to search from whole array 

[]
False


True

In [66]:
# Setting all the elements of an array to 0
a = np.zeros((100, 100))
np.all(a == 0)

True

In [72]:
# conditional function 
a = np.array([51, 2, 25, 2])
b = np.array([52, 2, 3, 2])
c = np.array([6, 4, 27, 5])
((a <= b) & (b <= c)).all() # it will check each element of both condition

False

In [76]:
# conditon usion or 
a = np.array([1, 12, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) | (b <= c)).all() # if one condition is true it will be true

True

In [80]:
# diagnol elements 
arr = np.eye(3) # eye functions makes all diagnol elements 1 and set remaining to 0
print(arr)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [79]:
arr1 = np.eye(3,4) # 3 rows 4 column no sequence because rows != column
print("here is rectangle array ")
arr1

here is rectangle array 


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [82]:
arr1 = np.eye(4,4) # We can mention rows and column. 4 rows 4 column 
print("here is square array ")
arr1

here is square array 


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [84]:
# diag: This function creates a two dimensional 
#array with all the diagonal elements as the given value
#and rest as 0 (in a square matrix).
arr = np.diag([21,25,43,7]) # thru diag function you can assign custom values to the diagnol elements remainig will be 0
arr

array([[21,  0,  0,  0],
       [ 0, 25,  0,  0],
       [ 0,  0, 43,  0],
       [ 0,  0,  0,  7]])

In [88]:
# get diagnol elements 
np.diag(arr) # make it function and pass array name as value
print("The diagnol elements are")
np.diag(arr)

The diagnol elements are


array([21, 25, 43,  7])

In [96]:
# This randomint funciton is used to generate integer values randomly
#number between a given range.
#The syntax is:
#randint(min,max,total_values)
arr = np.random.randint(-10,10,5) # at every execution value will be diffrent
arr

array([ 3, -8,  1,  3, -1])

In [97]:
# This simple rand function generate floating values randomly from 0 to 1
#between 0 to 1
#The syntax is: 
#rand(number_of_values)
arr = np.random.rand(5)
arr

array([0.89711516, 0.25989921, 0.83522426, 0.26577158, 0.87782799])

In [98]:
arr = np.random.rand(2, 3) # generate random float numbers in 2D array format as well
arr

array([[0.4156052 , 0.79640612, 0.06351059],
       [0.73787103, 0.96936345, 0.42122251]])

In [114]:
#This randn function generate random values can be any
#This may return positive or negative numbers as well.
#The syntax is:
#randn(number_of_values)
arr = np.random.randn(3)  # value can be any
arr

array([-1.2009697 , -1.32197719,  1.35605793])

In [124]:
# There would be a starting point and an ending point along
#with the interval value.
arr = np.arange(-25,25,5) # np.arange(starting value , end value , increment_value)
arr

array([-25, -20, -15, -10,  -5,   0,   5,  10,  15,  20])

In [126]:
# it will automatically be incremented by 1
arr = np.arange(-2, 17)
arr

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
       15, 16])

In [129]:
# sin. Print sine of one angle:
np.sin(np.pi/4)

0.7071067811865476

In [142]:
# Print sines of an array of angles given in degrees:
np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180. ) # ask the teacher about pi function

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [139]:
print(np.pi)

3.141592653589793


In [143]:
#Method 16: cos.
np.cos(np.array([0, np.pi/2, np.pi]))

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [146]:
#Method 16: tan
from math import pi
np.tan(np.array([-pi,pi/2,pi])) # logic is not clear

array([ 1.22464680e-16,  1.63312394e+16, -1.22464680e-16])

In [164]:
#Method 17: round.
np.round(16.0955, 3), round(16.0965, 3) # np.round(value, number_decimal_values)

(16.096, 16.096)

In [165]:

#Method 18: floor. Return the floor of the input, element-wise.
#The floor of the scalar x is the largest integer i, such that i <= x.
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.floor(a)# round to lower value

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

In [167]:

#Method 18: floor. Return the floor of the input, element-wise.
#The floor of the scalar x is the largest integer i, such that i <= x.
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.ceil(a)# round to upper value

array([-1., -1., -0.,  1.,  2.,  2.,  2.])

In [169]:
# the fractional part of the signed number x is discarded.
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.trunc(a) # Truncate the decimal value

array([-1., -1., -0.,  0.,  1.,  1.,  2.])

In [170]:
np.prod([]) # PRoduct of empty arrays = 1

1.0

In [186]:
np.prod([[2.,3.,4],[2.,4.,5]]) # 2 dimentional array multiplys 1st element to the next and so on but number of col must be equal

960.0

In [204]:
# cumsum. Return the cumulative sum of the elements along a given axis.
a = np.array([[[1,2,3], [4,5,6],[7,8,9]]])
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [205]:
np.cumsum(a,axis=1)# ADDS 1ST ROW TO THE NEXT

array([[[ 1,  2,  3],
        [ 5,  7,  9],
        [12, 15, 18]]], dtype=int32)

In [203]:
np.cumsum(a,axis=2)# ADDS 1ST COL TO THE NEXT

array([[[ 1,  3,  6],
        [ 4,  9, 15],
        [ 7, 15, 24]]], dtype=int32)

In [209]:
# lcm. Returns the lowest common multiple of |x1| and |x2|
np.lcm(3, 2)

6

In [216]:
# gcd. Returns the lowest common divider of |x1| and |x2|
np.gcd(4, 18)

2

In [226]:
# transpose. Reverse or permute the axes of an array; returns the modified array
x = np.arange(6).reshape((2, 3)) # can be molded to require shape
x

array([[0, 1, 2],
       [3, 4, 5]])

In [227]:
np.transpose(x) # five the transpose

array([[0, 3],
       [1, 4],
       [2, 5]])

In [228]:
# capitalize. Return a copy of a with only the first character of each element capitalized.
c = np.array(['a1b2','1b2a','b2a1','2a1b'],'S4'); c

array([b'a1b2', b'1b2a', b'b2a1', b'2a1b'], dtype='|S4')

In [230]:
np.char.capitalize(c) # capitalize the 1st letter

array([b'A1b2', b'1b2a', b'B2a1', b'2a1b'], dtype='|S4')

In [233]:
d = np.char.upper(c)

In [234]:
d

array([b'A1B2', b'1B2A', b'B2A1', b'2A1B'], dtype='|S4')

In [235]:
e = np.char.lower(d)

In [236]:
e

array([b'a1b2', b'1b2a', b'b2a1', b'2a1b'], dtype='|S4')

In [245]:
c = np.array(['aAaAaA', '  aA  ', 'abBABba'])
d = np.char.count(c,'BA')
d

array([0, 0, 1])

In [254]:
# linspace. This function returns values 
#between a given range and with a same gap between
#consecutive elements.
np.linspace(1,15,30)

array([ 1.        ,  1.48275862,  1.96551724,  2.44827586,  2.93103448,
        3.4137931 ,  3.89655172,  4.37931034,  4.86206897,  5.34482759,
        5.82758621,  6.31034483,  6.79310345,  7.27586207,  7.75862069,
        8.24137931,  8.72413793,  9.20689655,  9.68965517, 10.17241379,
       10.65517241, 11.13793103, 11.62068966, 12.10344828, 12.5862069 ,
       13.06896552, 13.55172414, 14.03448276, 14.51724138, 15.        ])

In [262]:
matrix = np.random.randint(0,8,9).reshape(3,3)
matrix

array([[7, 1, 0],
       [3, 5, 4],
       [1, 5, 1]])

In [263]:
np.min(matrix, axis=1) #finds row wise min

array([0, 3, 1])

In [264]:
np.max(matrix, axis=0) #finds col wise max

array([7, 5, 4])

In [265]:
np.sum(matrix, axis=1) #finds row wise sum

array([ 8, 12,  7])

In [268]:
np.sum(matrix, axis=0) #finds col wise sum

array([11, 11,  5])

In [269]:
np.cumsum(matrix) #finds cumulative sum

array([ 7,  8,  8, 11, 16, 20, 21, 26, 27], dtype=int32)

In [278]:
# shuffle. shuffle the array elements.
np.random.seed(122) # logic not clear
arr = np.random.randint(1,21,10)
arr

array([16, 11, 13, 17, 13, 16,  3, 16, 11, 10])

In [279]:
np.random.shuffle(arr)
arr

array([13, 16, 16, 11, 16, 10, 11, 13, 17,  3])

In [280]:
# unique. displays unique number of the array.
np.unique(arr)

array([ 3, 10, 11, 13, 16, 17])

In [299]:
# argsort. prints the sorted index value wise ascending
one = np.array([5,4,2,6])
one


array([5, 4, 2, 6])

In [303]:
ASSENDING = one.argsort() #PRINT THE ORDER OF VALUES LOWER TO HIGER

In [304]:
ASSENDING

array([2, 1, 0, 3], dtype=int64)

In [319]:
x = [[1,2,3],[4,0,6],[7,1,0]]
arr = np.array(x)
arr

array([[1, 2, 3],
       [4, 0, 6],
       [7, 1, 0]])

In [320]:
np.where(arr >= 4) # logic not clear

(array([1, 1, 2], dtype=int64), array([0, 2, 0], dtype=int64))

In [321]:
# count_nonzero
np.count_nonzero(arr)

7

In [322]:
# sort. It is used to sort an array
a = np.array([[1,4], [3,1]])
a

array([[1, 4],
       [3, 1]])

In [324]:
a.sort(axis=1) # sort inside row
a

array([[1, 4],
       [1, 3]])

In [327]:
a.sort(axis=0)
a

array([[1, 3],
       [1, 4]])

In [338]:
# variance. var.
a = np.array([[1, 2], [4, 0]])
np.var(a)# logic not clear

2.1875

In [348]:
# Split. Split an array into 
#multiple sub-arrays as views into ary.
x = np.arange(16.0)
np.split(x, 4)

[array([0., 1., 2., 3.]),
 array([4., 5., 6., 7.]),
 array([ 8.,  9., 10., 11.]),
 array([12., 13., 14., 15.])]

In [353]:
x = np.arange(10.0)
np.split(x, [3,5,6,15])

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7., 8., 9.]),
 array([], dtype=float64)]

In [357]:
# delete. Return a new array with sub-arrays along an axis deleted. For a one dimensional array, this returns those
#entries not returned by arr[obj].
arr = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [364]:
np.delete(arr, 0, 0)

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])